### ISSUE TITLE
where is the "data" directory and its files?

### ISSUE THREAD

**Issue by MrRace** [PierreGe/RL-movie-recommender#2]
Hi @PierreGe 
From your code we can see your raw data include "imdb_database.json" , how to get it? Could you please tell some more details about it? Where is the raw data and is there a script to do the translation?
Thanks a lot!

**Comment by PierreGe** [comment]
Unfortunately, I do not own the right to share this file.
However, you can try to find a similar dataset on the internet and transform it to match this one following this repository : https://github.com/oxplot/imdb2json
